/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.smeup.rpgclient

import com.smeup.rpgparser.execution.ResourceProgramFinder
import com.smeup.rpgparser.execution.executePgmWithStringArgs
import com.smeup.rpgparser.rgpinterop.RpgSystem

fun main(args: Array<String>) {
    RpgSystem.addProgramFinder(ResourceProgramFinder("/"))
    executePgmWithStringArgs("HELLO", emptyList())
}
